### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [Lio-n/dwf-m8-desafio#1]
Buenas Leo, ¿Como va?

Estuve revisando el desafío y te dejo algunas cosas que vi:

El login estaría copado poder cambiar el nombre de usuario o la password de forma independiente, o sea para cambiar la pass me requiere que también complete el nombre de usuario y lo modifique.

Otra cosa que me paso, es que en mobile no se me cierra el desplegable del menú cuando clickeo en una ruta como lo hace en modo desktop (es por el hover).

La verdad que hasta ahora puedo decir que es el mejor desafío que me toco ver del mod8, re contra mil felicitaciones porque funciona  todo y lo mejor es que funciona rápido 

Éxitos en el mod9!

**Comment by Lio-n** [comment]
Buenas @FerDR89.
Con el tema de actualizar el nombre del usuario o la contraseña de forma independiente. Estaría tendiendo un problema, porque el endpoint que utilizo para actualizar los datos seria este:

``````
const updateUserAPI = ({ full_name, token, password }: UpdateUserParams): void => {
  fetch(`${API_BASE_URL}/user/update`, {
    method: "put",
    headers: {
      "content-type": "application/json",
      Authorization: `bearer ${token}`,
    },
    body: JSON.stringify({ full_name, password }),
  });
};
``````

El cual requiere ambos datos (full_name, password).
Por ahora solo le añadí el nombre del user como un defaultValue en el input.

Con respecto al tema del despliegue del menú, usando :focus en lugar de :hover en mobile funciona bien, pero en desktop no.
Me voy a fijar bien eso.

Y por ultimo Muchas Gracias por el feedback!
Me re sirve, Thx!
